"""Initial migration

Revision ID: 668e2bd0edd6
Revises:
Create Date: 2026-03-24 11:25:34.069291

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "668e2bd0edd6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ==============================================================================
# EDUCATIONAL NOTE: A Proper Baseline Migration
# The first revision in a migration chain must build the schema from scratch
# (CREATE TABLE), so that `alembic upgrade head` works on a fresh, empty
# database. An earlier version of this revision only ALTERed columns of a
# pre-existing `users` table, which failed on fresh databases ("no such table")
# and on SQLite (no ALTER COLUMN support). This rewrite was autogenerated
# against an empty database so it exactly matches the `User` SQLModel in
# database.py — the same schema `SQLModel.metadata.create_all()` produces.
#
# Databases whose schema was already created by `create_all()` (the server does
# this at startup) should be marked as current without re-running this
# revision:  `alembic stamp head`
# ==============================================================================


def upgrade() -> None:
    """Upgrade schema: create the users table from scratch."""
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Downgrade schema: drop the users table."""
    op.drop_table("users")
